# Intents
    # Get Capacity of Gym: 0
    # Get Most Crowded Gym: 1
    # Get Least Crowded Gym: 2
    # Get Best Time to Visit Gym: 3

data = [
    ("What is the average capacity of Tampines Gym on weekends?", 0),
    ("Show me the capacity of Ang Mo Kio gym on a weekday at 7am", 0),
    ("How crowded is Bishan ActiveSG Gym at 1800?", 0),
    ("Tell me the average occupancy of Kallang Basin Gym ActiveSG on a Saturday", 0),
    ("What’s the typical crowd like at Serangoon Central Gym on weekdays?", 0),
    ("Is the gym at Toa Payoh West crowded on weekdays at 12pm?", 0),
    ("Give me the average capacity for Yishun ActiveSG Gym at 10am", 0),
    ("How busy is Clementi ActiveSG on Sundays?", 0),
    ("Show average usage of Jurong East Gym on weekends", 0),
    ("Capacity of Katong ActiveSG on weekday at 4pm?", 0),
    ("Can you tell me the occupancy at Sengkang Gym on Saturdays?", 0),
    ("How full is Bukit Canberra gym on weekdays at 13:00?", 0),
    ("What's the average attendance at Bukit Batok gym on Wednesdays at 1100?", 0),
    ("Capacity levels at Jurong Lake Gardens Gym on weekends?", 0),
    ("Show me how crowded Bedok ActiveSG gym gets during the evening", 0),

    ("Which gym is the least crowded at 6pm?", 1),
    ("Where can I find the emptiest gym on weekdays?", 1),
    ("Show me the gym with the lowest occupancy at 12:00", 1),
    ("Which ActiveSG gym has the fewest people on Saturday?", 1),
    ("What's the best gym to go to if I want to avoid the crowd at 2pm?", 1),
    ("Where is it the quietest among all gyms?", 1),
    ("Find the most empty gym", 1),
    ("Which gym has the smallest number of users at 1500?", 1),
    ("Tell me the least busy gym at 2pm", 1),
    ("Which gym has the lowest capacity at 9PM?", 1),
    ("Where can I go to avoid crowds in ActiveSG gyms?", 1),
    ("Most peaceful gym currently?", 1),
    ("I want a gym that's empty on weekends— any suggestions?", 1),
    ("List the top 3 least crowded gyms nat 7pm", 1),
    ("Which gym has the lowest usage on weekends?", 1),

    ("Which gym is the most crowded on Sunday 6pm?", 2),
    ("Show me the gym with the highest occupancy during weekday 11am", 2),
    ("Where is it busiest among ActiveSG gyms on a Saturday?", 2),
    ("Find the most crowded gym on weekends", 2),
    ("What gym has the highest capacity usage on Friday at 4pm?", 2),
    ("Tell me which gym is packed on Saturday mornings", 2),
    ("Which ActiveSG gym is fully packed at 2pm?", 2),
    ("List the gyms with the most users on weekday", 2),
    ("Where are the biggest crowds on Sunday at 9am?", 2),
    ("Where is it most packed during weekday at 6pm?", 2),
    ("Which gym location is extremely crowded during Saturday 8pm?", 2),
    ("I want to avoid the most crowded gym on weekends — which one is it?", 2),
    ("Which gym has the worst crowd on Sunday at 9pm?", 2),
    ("Which gym is packed on a weekday at 7pm?", 2),
    ("What gym is extremely busy on Friday at 10pm?", 2),

    ("When is the best time to go to Bishan gym?", 3),
    ("What's a good time to visit Kallang Basin Gym on weekdays?", 3),
    ("Tell me the least crowded time for Yishun ActiveSG Gym", 3),
    ("Best time of day on weekends to work out at Woodlands Gym?", 3),
    ("When should I go to avoid crowds at Tampines Gym?", 3),
    ("When is Fernvale Square Gym usually quiet?", 3),
    ("What is the best time to go gyming at Serangoon?", 3),
    ("When is it not busy at Jurong West Gym?", 3),
    ("Suggest a low-crowd time for ActiveSG Gym @ Toa Payoh on Saturday", 3),
    ("What time is Bukit Canberra usually not crowded?", 3),
    ("Quietest time to go to Katong Gym on Friday?", 3),
    ("When can I go to Delta Gym with few people around?", 3),
    ("I want to avoid crowds on Thursday — when should I go gym?", 3),
    ("When does Bedok Gym have the least number of people on weekdays?", 3),
    ("Suggest best hour for a calm workout at Bukit Batok Gym", 3)
]